app/Http/routes.php
<?php
use App\Http\Requests;
use Illuminate\Http\Request;

use App\Role;
use App\User;
use App\Module;
use App\Permission;
use App\PermissionType;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');



Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
 
// Registration routes...
//Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', ['as' => 'auth/register', 'uses' => 'Auth\AuthController@postRegister']);



Route::get('/', function () {
    return view('layouts/master');
});
Route::get('/home', function () {
    return view('layouts/master');
});

Route::group(['prefix' => 'admin','middleware' => 'auth','namespace'=>'Admin'], function () {
	Route::resource('user','UserController');
	Route::resource('roles','RolesController');
	Route::resource('rol/permission','PermissionsController');
	/*Route::get('user/create','UserController@create');	
	Route::post('user/store','UserController@postRegister');	*/
});
Route::get('permissions_role', function(Request $request){
	if($request->ajax()){
		$role = $request->role;
		$rol_permission = Role::find($role)->permission()->get();
		return $rol_permission;
	}
});
Route::get('permissions_role_update', function(Request $request){
	if($request->ajax()){
		$role 		= $request->role;
		$permission = $request->permission;
		$status 	= $request->status;

		$role 		= Role::find($role);
		$perm_obj 	= Permission::where('slug','=',$permission)->first();
		if( $status == 'true' ){
			$role->attachPermission($perm_obj->id); // permission attached to a role
		}else{
			$role->detachPermission($perm_obj->id); // permission attached to a role
		}
	}
});

Route::get('permissions_user', function(Request $request){
	if($request->ajax()){
		$user = $request->user;
		$role = User::find($user)->roles()->first();

		$permission['role'] = Role::find($role->id)->permission()->get();
		$permission['user'] = User::find($user)->permission()->get();

		return $permission;
	}
});

Route::get('permissions_user_update', function(Request $request){
	if($request->ajax()){
		$user 		= $request->user;

		$permission = $request->permission;
		$status 	= $request->status;
		$user 		= User::find($user);
		$perm_obj 	= Permission::where('slug','=',$permission)->first();

		if( $status == 'true' ){
			$user->attachPermission($perm_obj->id); // permission attached to a role
		}else{
			$user->detachPermission($perm_obj->id); // permission attached to a role
		}
	}
});

app/Role.php
<?php

namespace App;

use Bican\Roles\Models\Role as Roles;

class Role extends Roles
{

	 /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'roles';

    protected $connection = 'pgsql';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name','slug','description','active'];

    /**
     * obtiene los permisos asociados a un Rol
     *
     * @var array
     */
    public function permission(){
        return $this->belongsToMany('App\Permission','permission_role','role_id','permission_id','permissions');
    }



}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Validator;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use App\Module;
use App\Role;

class RolesController extends Controller
{
    private $slug = "users"; //slug usuado para obtener los permisos asociados a este controlador en la tabla permissions
    private $user;
    public function __construct(){
        $this->user = \Auth::user();
       // $miModule = new Module();
       // dd
        //$module = Module::getPermissionsBySlug($this->slug); //where('slug', $this->slug)->get();
        //$module = Module::where('id',1);
        
        //$this->middleware('permission:create|delete');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        #VERIFICAMOS PERMISOS PARA VISUALIZAR ESTE MODULO
        /*if (!$this->user->can('roles.view')){
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }*/

        #CONSULTAMOS LA DATA Y LA ENVIAMOS A LA VISTA
        $valor = $request->input('search');
        //dd($valor);
        $roles = Role::where('name','like',"%$valor%")
                        ->orWhere('slug','like',"%$valor%")
                        ->paginate(10);
        return view('admin.roles.index',compact('roles','request'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO
        /*if (!$this->user->can('roles.view')){
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }*/
        
        return view('admin.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        #VERIFICAMOS PERMISOS PARA GUARDAR UN NUEVO REGISTRO
        /*if (!($this->user->can('user.create'))) {
            notify()->flash('No posee permisos para guardar en este modulo!', 'error', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
            return back()->withInput();
        }*/

        #VALIDAMOS LA DATA DE ENTRADA SEAN CORRECTA
        $validator = Validator::make($request->all(),[
            'name'          => 'required|max:35',
            'slug'          => 'required|max:35',
            'description'   => 'required|max:50',
        ]);
        
        if ($validator->fails()) {
            return redirect('admin/roles/create')
                        ->withErrors($validator)
                        ->withInput();
        }

        #PROCEDEMOS CON EL REGISTRO, SI EL MISMO GENERA UN ERROR SE ENVIA UNA NOTIFICACIÓN POR PANTALLA
        try {
            Role::create([
                'name'          => $request->name,
                'slug'          => $request->slug,
                'description'   => $request->description,
            ]);
            notify()->flash('Su registro fue realizado!', 'success', [
                'timer'     => 3000,
                'text'      => '',
            ]);
            return view('admin.roles.create');
        }catch(\Illuminate\Database\QueryException $e){
            notify()->flash('Su registro no fue realizado!', 'error', [
                'timer' => 3000,
                'text' => 'Ocurrio un error, por favor revise los datos',
            ]);
            return back()->withErrors($validator)->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO Y SUS DATOS
        /*if (!($this->user->can('roles.view'))) {
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
            return back()->withInput();
        }*/

        #REALIZAMOS LA CONSULTA DEL USUARIO O LA PERSONA
        $rol = Role::findOrFail($id);
        return view('admin.roles.show',compact('rol'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO Y SUS DATOS
        /*if (!($this->user->can('roles.view'))) {
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }*/

        #REALIZAMOS LA CONSULTA DEL USUARIO O LA PERSONA
        $rol = Role::findOrFail($id);
        
        return view('admin.roles.edit',compact('rol'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        #VERIFICAMOS EL PERMISO CORRESPONDIENTE PARA ACTUALIZAR
        /*if (!($this->user->can('role.edit'))) { 
            notify()->flash('No posee permisos para modificar este modulo!', 'error', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }*/

        #VALIDAMOS LOS DATOS DE ENTRADA SEAN CORRECTOS
        $validator = Validator::make($request->all(),[
            'name' => 'required|max:35',
            'slug' => 'required|max:35',
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        #PROCEDEMOS CON LA ACTUALIZACIÓN, SI EL PROCEDIMIENTO GENERA UN ERROR ESTE ENVIA UN MENSAJE CORRESPONDIENTE
        try {
            $rol = Role::find($id);
            $rol->name          = $request->name;
            $rol->slug          = $request->slug;
            $rol->description   = $request->description;
            $rol->active        = $request->active;
            $rol->save();

            notify()->flash('Su modificación fue realizado!', 'success', [
                'timer' => 3000,
                'text' => '',
            ]);
            return back()->withInput();
        }catch(\Illuminate\Database\QueryException $e){
            notify()->flash('Su registro no fue realizado!', 'error', [
                'timer' => 3000,
                'text' => 'Ocurrio un error, por favor revise los datos',
            ]);
            return back()->withErrors($validator)->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.title.roles')}}
@endsection

@section('subtitulo')
	{{trans('app.title.create')}}
@endsection

@section('formulario')

<div class="x_content"><br/>
	<form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" action={{ route('admin.roles.store') }} method="post">
		{!! csrf_field() !!}
		@include('partials.menssage_error')

		@include('admin.roles.partials.fields',['status'=>''])
		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<a href="{{ URL::previous() }}" class="btn btn-primary">{{trans('app.attribute.cancel')}}</a>
				<button type="submit" class="btn btn-primary">{{trans('app.button.save')}}</button>
			</div>
		</div>
	</form>
</div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.title.roles')}}
@endsection

@section('subtitulo')
	{{trans('app.title.edit')}}
@endsection


@section('formulario')
<div class="x_content"><br/>
	<form data-parsley-validate class="form-horizontal form-label-left" action="{{route('admin.roles.update',$rol->id)}}" method="POST" accept-charset="utf-8">

		@include('partials.menssage_error')
	
		<input type="hidden" name="_method" value="PUT">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		@include('admin.roles.partials.fields',['status'=>''])

		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.status')}} <span class="required">*</span></label>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<p>	{{trans('app.attribute.active')}}:<input type="radio" class="flat" name="active" id="statusA" value="1" {!! $rol->active?"checked=":null !!} required /> 
					{{trans('app.attribute.locked')}}:<input type="radio" class="flat" name="active" {!! $rol->active!=1?"checked=":null !!} id="statusB" value="0" />
				</p>
			</div>
		</div>
		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<a href="{{ URL::previous() }}" class="btn btn-primary">{{trans('app.button.cancel')}}</a>
				<button type="submit" class="btn btn-primary">{{trans('app.button.edit')}}</button>
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts/master_form')

@section('titulo')
	{{trans('app.title.roles')}}
@endsection

@section('subtitulo')
	{{trans('app.title.find')}}
@endsection

@section('formulario')
<!-- BOTON BUSCAR-->
<div class="col-md-12">
	<form action="{!! url('/admin/roles') !!}" method="get" accept-charset="utf-8">
		<div class="row">
		<div class="col-sm-4" style="border:0px solid red">
			<p><a href="{{url('admin/roles/create')}}" class="btn btn-primary">{{trans('app.attribute.create')}} {{trans('app.attribute.rol')}}</a>	</p>
		</div>
		<div class="col-sm-8" style="border:0px solid red">
			<div class="input-group">
				<input type="text" name='search' class="form-control" required="" value="{{$request->search}}">
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">{{trans('app.button.find')}}</button>
				</span>
			</div>
		</div>
		</div>

	</form>
</div>

<!-- TABLA DE REGISTROS-->
<div class="col-md-12">
	@include('admin.roles.partials.list',['status'=>''])
</div>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.attribute.roles')}}
@endsection

@section('subtitulo')
	{{trans('app.attribute.view')}}
@endsection


@section('formulario')
<div class="x_content"><br/>
	<form data-parsley-validate class="form-horizontal form-label-left" action="{{url('admin.roles.edit')}}" method="get" accept-charset="utf-8">
		@include('admin.roles.partials.fields',['status'=>'disabled'])

		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.status')}} <span class="required">*</span></label>
			<div class="col-md-6 col-sm-6 col-xs-12">
			<p>{!! $rol->active?"<div class='alert alert-success' role='alert'><strong>Activo</strong></div>":"<div class='alert alert-danger' role='alert'><strong>Bloqueado</strong></div>" !!}</p>
        	</div>
		</div>

		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<a href="{{ URL::previous() }}" class="btn btn-primary">{{trans('app.attribute.cancel')}}</a>
				<a href="{{route('admin.roles.edit',$rol->id)}}" class="btn btn-primary" role='button' >{{trans('app.attribute.edit')}}</a>
			</div>
		</div>
	</form>
</div>
@endsection