app/Http/routes.php
<?php
use App\Http\Requests;
use Illuminate\Http\Request;

use App\Role;
use App\User;
use App\Module;
use App\Permission;
use App\PermissionType;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');



Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
 
// Registration routes...
//Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', ['as' => 'auth/register', 'uses' => 'Auth\AuthController@postRegister']);



Route::get('/', function () {
    return view('layouts/master');
});
Route::get('/home', function () {
    return view('layouts/master');
});

Route::group(['prefix' => 'admin','middleware' => 'auth','namespace'=>'Admin'], function () {
	Route::resource('user','UserController');
	Route::resource('roles','RolesController');
	Route::resource('rol/permission','PermissionsController');
	/*Route::get('user/create','UserController@create');	
	Route::post('user/store','UserController@postRegister');	*/
});
Route::get('permissions_role', function(Request $request){
	if($request->ajax()){
		$role = $request->role;
		$rol_permission = Role::find($role)->permission()->get();
		return $rol_permission;
	}
});
Route::get('permissions_role_update', function(Request $request){
	if($request->ajax()){
		$role 		= $request->role;
		$permission = $request->permission;
		$status 	= $request->status;

		$role 		= Role::find($role);
		$perm_obj 	= Permission::where('slug','=',$permission)->first();
		if( $status == 'true' ){
			$role->attachPermission($perm_obj->id); // permission attached to a role
		}else{
			$role->detachPermission($perm_obj->id); // permission attached to a role
		}
	}
});

Route::get('permissions_user', function(Request $request){
	if($request->ajax()){
		$user = $request->user;
		$role = User::find($user)->roles()->first();

		$permission['role'] = Role::find($role->id)->permission()->get();
		$permission['user'] = User::find($user)->permission()->get();

		return $permission;
	}
});

Route::get('permissions_user_update', function(Request $request){
	if($request->ajax()){
		$user 		= $request->user;

		$permission = $request->permission;
		$status 	= $request->status;
		$user 		= User::find($user);
		$perm_obj 	= Permission::where('slug','=',$permission)->first();

		if( $status == 'true' ){
			$user->attachPermission($perm_obj->id); // permission attached to a role
		}else{
			$user->detachPermission($perm_obj->id); // permission attached to a role
		}
	}
});

app/User.php
<?php

namespace App;



use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;


//bican
use Bican\Roles\Traits\HasRoleAndPermission;
use Bican\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;



class User extends Model implements AuthenticatableContract, CanResetPasswordContract, HasRoleAndPermissionContract
{
    use Authenticatable, CanResetPassword, HasRoleAndPermission;

    
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    protected $connection = 'pgsql';

    //protected $connection = 'admin';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name','last_name','email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function roles(){
        return $this->belongsToMany('App\Role','role_user','user_id','role_id','roles');
    }

    public function permission(){
        return $this->belongsToMany('App\Permission','permission_user','user_id','permission_id','permissions');
    }

    public function session()
    {
        return $this->hasMany('App\Session','user_id', 'id');
    }

    public function scopeSessions($query){
        return $query->leftJoin('sessions', 'sessions.user_id', '=', 'users.id');
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use App\Module;
use App\Role;
use App\PermissionType;
use App\Session;
use Carbon\Carbon;

class UserController extends Controller
{
    private $slug = "users"; //slug usuado para obtener los permisos asociados a este controlador en la tabla permissions
    private $user;
    
    public function __construct(){
        $this->user = \Auth::user();
       // $miModule = new Module();
       // dd
        //$module = Module::getPermissionsBySlug($this->slug); //where('slug', $this->slug)->get();
        //$module = Module::where('id',1);
        
        //$this->middleware('permission:create|delete');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO
        if (!$this->user->can('user.view')){
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);

           return back()->withInput();
        }

        #CONSULTAMOS LA DATA Y LA ENVIAMOS A LA VISTA
        $valor = $request->input('search');


        $users = User::where('name','like',"%$valor%")
                        ->orWhere('email','like',"%$valor%")
                        ->paginate(10);
        
        //CAPTURAMOS DATOS PARA DASHBOARD USUARIO
        $usuarios['total']           = User::all()->count(); //USUARIOS ACTIVOS
        $usuarios['bloqueados']      = User::where('active','=',false)->count(); //USUARIOS BLOQUEADOS
        $usuarios['usuarios_nuevos'] = User::where('created_at','>',Carbon::now()->addDays(-3)->toDateTimeString())->count(); //NUEVOS USUARIOS CON MENOS DE 3 DIAS DE SER INGRESADOS
    
        //dd($users->items());
        //dd($users->items()->attributes());

        return view('admin.user.index',compact('users','request','usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO
        if (!$this->user->can('user.view')){
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }
        
        $roles = Role::where('active','=',true)->get();
        return view('admin.user.create',compact('roles'));
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        #VERIFICAMOS PERMISOS PARA GUARDAR UN NUEVO REGISTRO
        if (!($this->user->can('user.create'))) {
            notify()->flash('No posee permisos para guardar en este modulo!', 'error', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
            return back()->withInput();
        }

        #VALIDAMOS LA DATA DE ENTRADA SEAN CORRECTA
        $validator = Validator::make($request->all(),[
            'name' => 'required|max:255',
            'last_name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
        
        if ($validator->fails()) {
            return redirect('admin/user/create')
                        ->withErrors($validator)
                        ->withInput();
        }

        #PROCEDEMOS CON EL REGISTRO, SI EL MISMO GENERA UN ERROR SE ENVIA UNA NOTIFICACIÓN POR PANTALLA
        try {
            User::create([
                'name'      => $request->name,
                'last_name' => $request->last_name,
                'email'     => $request->email,
                'active'    => true,
                'password'  => bcrypt($request->password),
            ]);
            notify()->flash('Su registro fue realizado!', 'success', [
                'timer'     => 3000,
                'text'      => '',
            ]);
            return view('admin.user.create');
        }catch(\Illuminate\Database\QueryException $e){
            notify()->flash('Su registro no fue realizado!', 'error', [
                'timer' => 3000,
                'text' => 'Ocurrio un error, por favor revise los datos',
            ]);
            return back()->withErrors($validator)->withInput();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,Request $request)
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO Y SUS DATOS
        if (!($this->user->can('user.view'))) {
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
            return back()->withInput();
        }

        #REALIZAMOS LA CONSULTA DEL USUARIO O LA PERSONA
        $usuario = User::findOrFail($id);
        $roles = Role::where('active','=',true)->get();
        $rol_user = User::find($id)->roles()->get();
        return view('admin.user.show',compact('usuario','roles','rol_user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        #VERIFICAMOS PERMISOS PARA VER ESTE MODULO Y SUS DATOS
        if (!($this->user->can('user.view'))) {
            notify()->flash('No posee permisos para visualizar este modulo!', 'info', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }

        $modules =  Module::all();
        $permission_type = PermissionType::orderBy('order','asc')->get();
        $mod_array_tree = parseTree($modules->toArray(),0);
        #REALIZAMOS LA CONSULTA DEL USUARIO O LA PERSONA
        $usuario = User::findOrFail($id);
        $rol_user = User::find($id)->roles()->get();
        $roles = Role::where('active','=',true)->get();

        return view('admin.user.edit',compact('usuario','roles','rol_user','mod_array_tree','permission_type'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        #VERIFICAMOS EL PERMISO CORRESPONDIENTE PARA ACTUALIZAR
        /*if (!($this->user->can('user.edit'))) { 
            notify()->flash('No posee permisos para modificar este modulo!', 'error', [
                'timer' => 3000,
                'text' => 'Los privilegios no son suficientes',
            ]);
           return back()->withInput();
        }*/

        #VALIDAMOS QUE EL USUARIO NO PUEDA MODIFICAR SUS PROPIO DATOS
        $user = \Auth::user();
        if($user->id==$id){
            notify()->flash('Su registro no fue realizado!', 'error', [
                'timer' => 3000,
                'text' => "El usuario no puede modificar sus propios datos desde este modulo",
            ]);
            return back()->withInput($request->except('password'));
        }

        #VALIDAMOS LOS DATOS DE ENTRADA SEAN CORRECTOS
        $validator = Validator::make($request->all(),[
            'name'      => 'required|max:255',
            'last_name' => 'required|max:255',
            'email'     => 'required|email|max:255',
            
        ]);

        #SI SE ESCRIBIÓ UN PASSWORD SE LE APLICA LA RESPECTIVA VALIDACION
        if($request->password!=''){
            $validator = Validator::make($request->all(),[
                'password' => 'required|confirmed|min:6',
            ]);
        }
        //EVITA QUE EL ROL CON SLUG 'admin' SEA MODIFICADO
        if($request->slug=='admin'){
            notify()->flash('Su registro no fue realizado!', 'error', [
                'timer' => 3000,
                'text' => "No se puede modificar el slug admin",
            ]);
        }

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput($request->except('password'));
        }

        #PROCEDEMOS CON LA ACTUALIZACIÓN, SI EL PROCEDIMIENTO GENERA UN ERROR ESTE ENVIA UN MENSAJE CORRESPONDIENTE
        try {
            $usuario = User::find($id);
            $usuario->name      = $request->name;
            $usuario->last_name = $request->last_name;
            $usuario->email     = $request->email;
            $usuario->password  = $request->password;
            $usuario->active    = $request->active;
            $usuario->save();    
        }catch(\Illuminate\Database\QueryException $e){
            notify()->flash('Su registro no fue realizado!', 'error', [
                'timer' => 3000,
                'text' => "Ocurrio un error, por favor revise los datos",
            ]);
            return back()->withErrors($validator)->withInput($request->except('password'));
        }
        $usuario->detachAllRoles(); //elimina el ó los roles asignados a un usuario
        $usuario->attachRole($request->rol); //asigna un nuevo rol al usuario
        notify()->flash('Su modificación fue realizado!', 'success', [
                'timer' => 3000,
                'text' => '',
        ]);
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *

resources/views/admin/user/create.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.attribute.user')}}
@endsection

@section('subtitulo')
	{{trans('app.attribute.create')}}
@endsection

@section('formulario')

<div class="x_content"><br/>
	<form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" action={{ route('admin.user.store') }} method="post">
		{!! csrf_field() !!}

		@include('partials.menssage_error')
		
		@include('admin.user.partials.fields', array(	'status'=>''))

		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.password')}} <span class="required">*</span></label>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<input type="password" name="password" class="form-control col-md-7 col-xs-12" {{ $status or "" }} >
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.password_confirmation')}}<span class="required">*</span></label>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<input type="password" name="password_confirmation" class="form-control col-md-7 col-xs-12" {{ $status or "" }} >
			</div>
		</div>


		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<a href="{{ URL::previous() }}" class="btn btn-primary">{{trans('app.attribute.cancel')}}</a>
				<button type="submit" class="btn btn-primary">{{trans('app.button.save')}}</button>
			</div>
		</div>
	</form>
</div>

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.title.user')}}
@endsection

@section('subtitulo')
	{{trans('app.title.edit')}}
@endsection


@section('formulario')
<div class="x_content"><br/>
	<form data-parsley-validate class="form-horizontal form-label-left" action="{{route('admin.user.update',$usuario->id)}}" method="POST" accept-charset="utf-8">

		@include('partials.menssage_error')
	
		<input type="hidden" name="_method" value="PUT">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		@include('admin.user.partials.fields',['status'=>'','mensaje'=>'Importante: Si no desea modificar la clave para este usuario deje los campos vacios'])
		
		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.status')}} <span class="required">*</span></label>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<p>	{{trans('app.attribute.active')}}:<input type="radio" class="flat" name="active" id="statusA" value="1" {!! $usuario->active?"checked=":null !!} required /> 
	    			{{trans('app.attribute.locked')}}:<input type="radio" class="flat" name="active" {!! $usuario->active!=1?"checked=":null !!} id="statusB" value="0" />
	    			@if(\Auth::user()->id!=$usuario->id)
	    				<a class="btn btn-success btn-sm v_modal" href="#" data-toggle="modal" data-target="#modal_permission"><i class="glyphicon glyphicon-lock"></i> Permisos</a>
	    			@endif
	    		</p>
                  
	    	</div>
    	</div>

    	<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.password')}} </label>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<input type="password" name="password" class="form-control col-md-7 col-xs-12" {{ $status or "" }} >
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.password_confirmation')}}</label>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<input type="password" name="password_confirmation" class="form-control col-md-7 col-xs-12" {{ $status or "" }} >
			</div>
		</div>

		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<a href="{{ URL::previous() }}" class="btn btn-primary">{{trans('app.attribute.cancel')}}</a>
				<button type="submit" class="btn btn-primary">{{trans('app.button.send')}}</button>
			</div>
		</div>
	</form>
</div>

<!-- Modal -->
@permission('permission.view')
<div id="modal_permission" class="modal fade" role="dialog">
 	<div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
			<div class="modal-header">

				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-lock"></span>{{trans('app.attribute.permission_user')}}</h4>
				<div class='alert alert-warning' role='alert' style='color:black'><strong>{{trans('app.attribute.nota_permi_user')}}</strong></div>
			</div>
			<div class="modal-body">
				<?php 
					$table = tablePermission($mod_array_tree,'',$permission_type);
				?>	
				<table class="table">
					<tr>
						<td>-</td>
						@foreach($permission_type as $type)
							<td align="center">{{$type['name']}}</td>
						@endforeach
					</tr>
					{!! $table !!}
				</table>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">{{trans('app.button.close')}}</button>
			</div>
		</div>
	</div>
</div>
@endpermission

@endsection

@section('metodos_js')
		
		$("#modal_permission").on('show.bs.modal', function () {
            var val = {{$usuario->id}}
			
			if(val!=''){

				$.get("/permissions_user?user=" + val,function(data){
			   		
				}).done(function(data) {
					console.log(data);
					$(':checkbox').prop("checked", false);
					
					$.each(data['role'], function( index, value ) {
						//alert( index + ": " + value['slug'] );
						id = value['slug'];
						id = id.replace(".", "-");

						$( '#'+id ).replaceWith( "<span class='glyphicon glyphicon-ok'></span>" );
						//$( '#'+id ).remove();
						//$('#'+id).prop("checked", true);

					});

					$.each(data['user'], function( index, value ) {
						alert( index + ": " + value['slug'] );

						id = value['slug'];
						id = id.replace(".", "-");

						//$( '#'+id ).remove();
						$('#'+id).prop("checked", true);

					});
				});
			}else{
				//$("#rol").empty();
			}
    	});

		$('.v_modal').click(function(){

			
		});

		$(':checkbox').change(function() {
        	//$('#textbox1').val($(this).is(':checked'));
        	var user = {{$usuario->id}}
        	var id = $(this).prop('id'); //refleja el ID del checkbox y tambien es el permiso
        	id = id.replace("-", ".");
        	var status = $(this).prop("checked");


        	$.get("/permissions_user_update?permission=" + id + "&status=" + status + "&user=" + user, function(data){
			   		
			}).done(function(data) {
				alert(data);
				new PNotify({
                            title: 'Actualización exitosa',
                            text: 'Su permiso fue actualizado con éxito',
                            type: 'success'
                        });
			});
    	});

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts/master_form')

@section('titulo')
	{{trans('app.attribute.user')}}
@endsection

@section('subtitulo')
	Lista de usuarios
@endsection

@section('formulario')
<!-- BOTON BUSCAR-->
<?php
/*$jsondata = '[{"id":1},{"id":2,"children":[{"id":5,"children":[{"id":7,"children":[{"id":8}]}]},{"id":4},{"id":6},{"id":9},{"id":10}]},{"id":3},{"id":11},{"id":12}]';
$obj = json_decode($jsondata);
dd($obj);*/

?>
	<div>
	<!-- TOTAL DE USUARIO-->
	<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
   		<div class="tile-stats">
      		<div class="icon"><i class="fa fa-user"></i></div>
          	<div class="count">{{$usuarios['total']}}</div>
          	<h3>{{trans('app.attribute.total_user')}}</h3>
		</div>
	</div>
	<!-- TOTAL DE USUARIO BLOQUEADO-->
	<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
   		<div class="tile-stats">
      		<div class="icon"><i class="glyphicon glyphicon-lock"></i></div>
          	<div class="count">{{$usuarios['bloqueados']}}</div>
          	<h3>{{trans('app.attribute.blocked_users')}}</h3>
		</div>
	</div>

	<!-- TOTAL DE USUARIO BLOQUEADO-->
	<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
   		<div class="tile-stats">
      		<div class="icon"><i class="glyphicon glyphicon-star"></i></div>
          	<div class="count">{{$usuarios['usuarios_nuevos']}}</div>
          	<h3>{{trans('app.attribute.new_users')}}</h3>
		</div>
	</div>

	</div>
<div class="col-md-12">

	<form action="{!! url('/admin/user') !!}" method="get" accept-charset="utf-8">
		<div class="row">
		<div class="col-sm-4" style="border:0px solid red">
			<p><a href="{{ route('admin.user.create') }}" class="btn btn-primary">{{trans('app.attribute.create')}} {{trans('app.attribute.user')}}</a>	</p>
		</div>
		<div class="col-sm-8" style="border:0px solid red">
			<div class="input-group">
				<input type="text" name='search' class="form-control" required="" value="{{$request->search}}">
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">{{trans('app.button.find')}}</button>
				</span>
			</div>
		</div>
		</div>

	</form>
</div>

<!-- TABLA DE REGISTROS-->
<div class="col-md-12">
	@include('admin.user.partials.list',['status'=>''])
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.attribute.user')}}
@endsection

@section('subtitulo')
	{{trans('app.attribute.view')}}
@endsection


@section('formulario')
<div class="x_content"><br/>
	<form data-parsley-validate class="form-horizontal form-label-left" action="{{url('admin.user.edit')}}" method="get" accept-charset="utf-8">
		@include('admin.user.partials.fields',['status'=>'disabled',])
		<!--INFO DEL ESTATUS-->
		
		<div class="form-group">
			<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{trans('app.attribute.status')}} <span class="required">*</span></label>
			<div class="col-md-6 col-sm-6 col-xs-12">
			<p>{!! $usuario->active?"<div class='alert alert-success' role='alert'><strong>Activo</strong></div>":"<div class='alert alert-danger' role='alert'><strong>Bloqueado</strong></div>" !!}</p>
        	</div>
		</div>

		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<a href="{{ URL::previous() }}" class="btn btn-primary">{{trans('app.attribute.cancel')}}</a>
				<a href="{{route('admin.user.edit',$usuario->id)}}" class="btn btn-primary" role='button' >{{trans('app.button.edit')}}</a>
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/admin/user/status.blade.php
@extends('layouts/master_form')


@section('titulo')
	{{trans('app.attribute.user')}}
@endsection

@section('subtitulo')
	Bloquar
@endsection


@section('formulario')
<div class="x_content"><br/>
	<form data-parsley-validate class="form-horizontal form-label-left" action="{{url('admin.user.edit')}}" method="get" accept-charset="utf-8">
		@include('admin.user.partials.fields',['status'=>'disabled'])

		<div class="ln_solid"></div>
		<div class="form-group">
			<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
				<button type="submit" class="btn btn-primary">{{trans('app.attribute.cancel')}}</button>
				<a href="{{route('admin.user.edit',$usuario->id)}}" class="btn btn-primary" role='button' >{{trans('app.button.edit')}}</a>
			</div>
		</div>
	</form>
</div>
@endsection